var gameList = {
  "game001": {
    "name": "Black Mesa",
    "price": "200000",
    "discount": "50",
    "photo": [
      "./images/Market/Black-mesa1.jpg",
      "./images/Market/Black-mesa2.jpg",
      "./images/Market/Black-mesa3.jpg",
      "./images/Market/Black-mesa4.jpg",
      "./images/Market/Black-mesa5.jpg"

    ],
    "logo": "./images/Market/Black-mesa-logo.jpg",
    "developer": "Crowbar Collective",
    "releaseDate": "2012-09-14",
    "platform": ["PC"],
    "genre": ["Phiêu lưu", "Hành động"],
    "ageRating": "18+",
    "information": "Black Mesa là dự án fanmade được Crowbar Collective phát triển nhằm tái hiện hoàn hảo câu chuyện Half‑Life với đồ họa hiện đại. Người chơi sẽ khám phá những hành lang tối tăm của trung tâm nghiên cứu Black Mesa, đối mặt với quái vật ngoài hành tinh, giải các câu đố vật lý và trải nghiệm cảm giác hồi hộp liên tục từ đầu đến cuối.",
  },

  "game002": {
    "name": "Outlast II",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Outlast1.jpg",
      "./images/Market/Outlast2.jpg",
      "./images/Market/Outlast3.jpg",
      "./images/Market/Outlast4.jpg",
      "./images/Market/Outlast5.jpg"
    ],
    "logo": "./images/Market/Outlast-logo.jpg",
    "developer": "Red Barrels",
    "releaseDate": "2017-04-25",
    "platform": ["PC", "PS", "Xbox"],
    "genre": ["Kinh dị"],
    "ageRating": "18+",
    "information": "Trong Outlast II, bạn sẽ vào vai nhà báo Blake Langermann điều tra một vụ mất tích bí ẩn ở vùng nông thôn Arizona. Game gây ấn tượng mạnh với bầu không khí u ám, âm thanh ma quái và cốt truyện tâm linh phức tạp. Người chơi phải dùng camera có đèn hồng ngoại để quan sát môi trường tối, trốn chạy khỏi những kẻ cuồng tín và tìm ra sự thật ẩn giấu.",
  },

  "game003": {
    "name": "Beyound Two Souls",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Beyound1.jpg",
      "./images/Market/Beyound2.jpg",
      "./images/Market/Beyound3.jpg",
      "./images/Market/Beyound4.jpg",
      "./images/Market/Beyound5.jpg",
    ],
    "logo": "./images/Market/Beyound-logo.jpg",
    "developer": "Quantic Dream",
    "releaseDate": "2013-10-08",
    "platform": ["PC", "PS"],
    "genre": ["Phiêu lưu", "Hành động"],
    "ageRating": "18+",
    "information": "Beyond Two Souls là một trải nghiệm điện ảnh tương tác, nơi bạn điều khiển Jodie Holmes, một cô gái gắn kết với thực thể siêu nhiên Aiden. Câu chuyện trải dài 15 năm, từ tuổi thơ cho đến tuổi trưởng thành, mang đến những tình huống sâu sắc về tình cảm, định mệnh và sức mạnh vô hình. Gameplay tập trung vào lựa chọn, quyết định của người chơi sẽ quyết định kết thúc của câu chuyện.",
  },

  "game004": {
    "name": "Subnautica",
    "price": "180000",
    "discount": "50",
    "photo": [
      "./images/Market/Subnautica1.jpg",
      "./images/Market/Subnautica2.jpg",
      "./images/Market/Subnautica3.jpg",
      "./images/Market/Subnautica4.jpg",
      "./images/Market/Subnautica5.jpg",
      ],
    "logo": "./images/Market/Subnautica-logo.jpg",
    "developer": "Unknown Worlds Entertainment",
    "releaseDate": "2018-01-23",
    "platform": ["PC", "PS", "Xbox", "Switch"],
    "genre": ["xây dựng", "Khám phá"],
    "ageRating": "12+",
    "information": "Subnautica đặt người chơi vào một hành tinh đại dương lạ lẫm sau khi tàu con thoi rơi. Người chơi phải thu thập tài nguyên, chế tạo dụng cụ, xây dựng căn cứ dưới nước và khám phá các sinh vật và công trình ngoài hành tinh. Đồ họa chân thực và soundtrack du dương tạo nên trải nghiệm sinh tồn đầy mê hoặc.",
  },

  "game005": {
    "name": "MouthWashing",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Mouthwashing1.jpg",
      "./images/Market/Mouthwashing2.jpg",
      "./images/Market/Mouthwashing3.jpg",
      "./images/Market/Mouthwashing4.jpg",
      "./images/Market/Mouthwashing5.jpg",
    ],
    "logo": "./images/Market/Mouthwashing-logo.jpg",
    "developer": "Wrong Organ",
    "releaseDate": "2024-09-26",
    "platform": ["PC"],
    "genre": ["Kinh dị"],
    "ageRating": "12+",
    "information": "Người chơi vào vai thành viên của phi hành đoàn tàu Tulpar bị mắc kẹt giữa không gian trong ánh hoàng hôn vĩnh cửu, phải đối mặt với cảnh tượng bạo lực, tàn phá và bí ẩn tâm linh bên trong khoang tàu tối tăm ",
  },

  "game006": {
    "name": "Left 4 Dead 2",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Left4dead1.jpg",
      "./images/Market/Left4dead2.jpg",
      "./images/Market/Left4dead3.jpg",
      "./images/Market/Left4dead4.jpg",
      "./images/Market/Left4dead5.jpg",
    ],
    "logo": "./images/Market/Left4dead-logo.jpg",
    "developer": "Valve",
    "releaseDate": "2009-11-17",
    "platform": ["PC", "Xbox"],
    "genre": ["FPS", "Kinh dị"],
    "ageRating": "18+",
    "information": "Left 4 Dead 2 tiếp nối thành công phần 1 với chiến dịch đông đảo zombie, vũ khí đa dạng và cơ chế phối hợp nhóm sâu sắc. Bốn người sống sót phải vượt qua những môi trường nguy hiểm như quán bar, khu quân sự và tàu hỏa để tìm đường sống sót.",
  },

  "game007": {
    "name": "Persona 5 Royal",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Persona1.jpg",
      "./images/Market/Persona2.jpg",
      "./images/Market/Persona3.jpg",
      "./images/Market/Persona4.jpg",
      "./images/Market/Persona5.jpg",
    ],
    "logo": "./images/Market/Persona-logo.jpg",
    
    "developer": "Atlus",
    "releaseDate": "2020-03-31",
    "platform": ["PS", "PC", "Switch"],
    "genre": ["Chiến thuật", "Cốt truyện"],
    "ageRating": "18+",
    "information": "Persona 5 Royal mang đến thêm các cung bậc cảm xúc với nhân vật mới Kasumi, thêm dungeon và sự kiện xã hội. Trải nghiệm lớp Phantom Thieves đánh cắp trái tim kẻ ác trong những phút kết hợp chiến đấu và cuộc sống học đường.",
  },

  "game008": {
    "name": "Schedule",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Schedule1.jpg",
      "./images/Market/Schedule2.jpg",
      "./images/Market/Schedule3.jpg",
      "./images/Market/Schedule4.jpg",
      "./images/Market/Schedule5.jpg",
    ],
    "logo": "./images/Market/Schedule-logo.jpg",
    "developer": "TVGS", 
    "releaseDate": "2025-03-25",
    "platform": ["PC"],
    "genre": ["Giả chiến"],
    "ageRating": "12+",
    "information": "Người chơi vào vai kẻ buôn ma túy nhỏ lẻ ở thành phố Hyland Point, dần xây dựng đế chế bất hợp pháp qua các khâu sản xuất, phân phối và quản lý nhân sự, tài sản rồi vươn lên thành ông trùm ngầm.",
  },

  "game009": {
    "name": "Middle Earth Shadow of War",
    "price": "1390000",
    "discount": "40",
    "photo": [
      "./images/Market/Middle1.jpg",
      "./images/Market/Middle2.jpg",
      "./images/Market/Middle3.jpg",
      "./images/Market/Middle4.jpg",
      "./images/Market/Middle5.jpg",
    ],
    "logo": "./images/Market/Middle-logo.jpg",
    "developer": "Monolith Productions",
    "releaseDate": "2017-10-10",
    "platform": ["PC", "PS", "Xbox"],
    "genre": ["Giả chiến"],
    "ageRating": "18+",
    "information": "Shadow of War tiếp tục câu chuyện của Talion và Celebrimbor qua cơ chế Nemesis, nơi kẻ thù nhớ và trả thù bạn theo từng lần sinh tồn. Open world rộng lớn cho phép tự do mạo hiểm và chiêu mộ quân lính Ork.",
  },

  "game010": {
    "name": "Diplomacy Is Not an Option",
    "price": "86000",
    "discount": "10",
    "photo": [
      "./images/Market/Diplomacy1.jpg",
      "./images/Market/Diplomacy2.jpg",
      "./images/Market/Diplomacy3.jpg",
      "./images/Market/Diplomacy4.jpg",
      "./images/Market/Diplomacy5.jpg",
    ],
    "logo": "./images/Market/Diplomacy-logo.jpg",
    
    "developer": "ControlMagic",
    "releaseDate": "2019-03-06",
    "platform": ["PC"],
    "genre": ["Xây dụng", "Giả chiến"],
    "ageRating": "12+",
    "information": "Diplomacy Is Not an Option là sự kết hợp giữa tower defense và real-time strategy, người chơi xây dựng pháo đài, điều khiển quân lính và chiến lược phòng thủ để chống lại các làn sóng kẻ thù.",
  },

  "game011": {
    "name": "Romance of The Three Kingdoms 8 Remake",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Romance1.jpg",
      "./images/Market/Romance2.jpg",
      "./images/Market/Romance3.jpg",
      "./images/Market/Romance4.jpg",
      "./images/Market/Romance5.jpg",
    ],
    "logo": "./images/Market/Romance-logo.jpg",
    "developer": "Koei Tecmo",
    "releaseDate": "2021-10-14",
    "platform": ["PC", "PS", "Switch", "Xbox"],
    "genre": ["giả chiến"],
    "ageRating": "12+",
    "information": "Phiên bản remake của ROTK 8 với đồ họa tân tiến, giữ nguyên cốt truyện lich sử và cơ chế chiến đấu trên bản đồ mở rộng.",
  },

  "game012": {
    "name": "Crusader Kings III",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Crusader1.jpg",
      "./images/Market/Crusader2.jpg",
      "./images/Market/Crusader3.jpg",
      "./images/Market/Crusader4.jpg",
      "./images/Market/Crusader5.jpg",
    ],
    "logo": "./images/Market/Crusader-logo.jpg",
    "developer": "Paradox Interactive",
    "releaseDate": "2020-09-01",
    "platform": ["PC"],
    "genre": ["Chiến thuật", "Cốt truyện"],
    "ageRating": "12+",
    "information": "Crusader Kings III đưa bạn vào vai một gia tộc trung cổ, kết hợp ngoại giao, hôn nhân, âm mưu và chiến tranh qua nhiều thế hệ để xây dựng đế chế của riêng mình.",
  },

  "game013": {
    "name": "Age of Empires IV Anniversary Edition",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/EmpiresIV1.jpg",
      "./images/Market/EmpiresIV2.jpg",
      "./images/Market/EmpiresIV3.jpg",
      "./images/Market/EmpiresIV4.jpg",
      "./images/Market/EmpiresIV5.jpg",
    ],
    "logo": "./images/Market/EmpiresIV-logo.jpg",
    "developer": "Relic Entertainment",
    "releaseDate": "2021-10-28",
    "platform": ["PC"],
    "genre": ["Chiến thuật", "Giả chiến"],
    "ageRating": "12+",
    "information": "Anniversary Edition kỷ niệm một năm phát hành, bổ sung thêm bản đồ mới, chiến dịch đặc biệt và cải tiến AI để thử thách cả người chơi cũ và mới.",
  },

  "game014": {
    "name": "Age of Empires II Definitive Edition",
    "price": "300000",
    "discount": "30",
    "photo": [
      "./images/Market/EmpiresII1.jpg",
      "./images/Market/EmpiresII2.jpg",
      "./images/Market/EmpiresII3.jpg",
      "./images/Market/EmpiresII4.jpg",
      "./images/Market/EmpiresII5.jpg",
    ],
    "logo": "./images/Market/EmpiresII-logo.jpg",
    "developer": "Forgotten Empires",
    "releaseDate": "2019-11-14",
    "platform": ["PC", "Xbox"],
    "genre": ["Chiến thuật", "Giả chiến"],
    "ageRating": "12+",
    "information": "Definitive Edition nâng cấp đồ họa lên 4K, thêm các bộ mở rộng và cải thiện giao diện người dùng để mang lại trải nghiệm mượt mà nhất.",
  },

  "game015": {
    "name": "Foundation",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Foundation1.jpg",
      "./images/Market/Foundation2.jpg",
      "./images/Market/Foundation3.jpg",
      "./images/Market/Foundation4.jpg",
      "./images/Market/Foundation5.jpg",
    ],
    "logo": "./images/Market/Foundation-logo.jpg",
    "developer": "Polymorph Games",
    "releaseDate": "2021-09-29",
    "platform": ["PC"],
    "genre": ["Xây dựng"],
    "ageRating": "12+",
    "information": "Foundation cung cấp cơ chế xây dựng thành phố không dựa trên lưới ô cố định, cho phép bạn thiết kế đô thị theo ý muốn và quản lý nhu cầu của dân cư.",
  },

  "game016": {
    "name": "Workers & Resources Soviet Republic",
    "price": "30000",
    "discount": "60",
    "photo": [
      "./images/Market/Soviet1.jpg",
      "./images/Market/Soviet2.jpg",
      "./images/Market/Soviet3.jpg",
      "./images/Market/Soviet4.jpg",
      "./images/Market/Soviet5.jpg",
    ],
    "logo": "./images/Market/Soviet-logo.jpg",
    "developer": "Build a Rocket Boy",
    "releaseDate": "2021-02-25",
    "platform": ["PC"],
    "genre": ["Xây dựng"],
    "ageRating": "12+",
    "information": "Trong Workers & Resources Soviet Republic, bạn sẽ đảm nhận vai trò quản lý kinh tế và hạ tầng của một quốc gia xã hội chủ nghĩa, đáp ứng nhu cầu hàng hóa và dịch vụ của đông đảo dân chúng.",
  },

  "game017": {
    "name": "Clair Obscur Expedition 33",
    "price": "700000",
    "discount": "15",
    "photo": [
      "./images/Market/331.jpg",
      "./images/Market/332.jpg",
      "./images/Market/333.jpg",
      "./images/Market/334.jpg",
      "./images/Market/335.jpg",
    ],
    "logo": "./images/Market/33-logo.jpg",
    "developer": "Kepler Interactive",
    "releaseDate": "",
    "platform": ["PC"],
    "genre": ["Chiến thuật", "Cốt truyện"],
    "ageRating": "12+",
    "information": "Trò chơi đặt bạn vào thế giới Belle Époque u tối, nơi nhóm tình nguyện viên của “Expedition 33” phải hợp lực để tiêu diệt thực thể siêu nhiên mang tên Paintress — kẻ gieo rắc “Gommage” mỗi năm, xoá sổ những ai vượt qua ngưỡng tuổi.",
  },

  "game018": {
    "name": "Grand Theft Auto V Enhanced",
    "price": "0",
    "discount": "0",
    "photo": [
      "./images/Market/Gta1.jpg",
      "./images/Market/Gta2.jpg",
      "./images/Market/Gta3.jpg",
      "./images/Market/Gta4.jpg",
      "./images/Market/Gta5.jpg",
    ],
    "logo": "./images/Market/Gta-logo.jpg",
    "developer": "Rockstar North",
    "releaseDate": "2013-09-17",
    "platform": ["PC", "PS", "Xbox"],
    "genre": ["Giả chiến", "Hành động"],
    "ageRating": "18+",
    "information": "Enhanced Edition tập trung cải thiện đồ họa và hiệu năng, mở rộng nội dung GTA Online và các bản cập nhật miễn phí liên tục từ Rockstar.",
  },

  "game019": {
    "name": "Fortnite",
    "price": "300000",
    "discount": "50",
    "photo": [
      "./images/Market/Fortnite_1.jpg",
      "./images/Market/Fortnite_2.webp",
      "./images/Market/Fortnite_3.webp",
      "./images/Market/Fortnite_4.jpg",
      "./images/Market/Fortnite_5.jpg"
    ],
    "logo": "./images/Market/Fortnite.jpg",
    "developer": "Epic Games",
    "releaseDate": "2017-07-25",
    "platform": ["PC", "PS", "Xbox", "Switch", "Mobile"],
    "genre": ["Hành động"],
    "ageRating": "12+",
    "information": "Fortnite liên tục cập nhật mùa mới, sự kiện in-game và hợp tác với các thương hiệu lớn, đem lại trải nghiệm đa dạng cho cộng đồng hàng triệu người chơi.",
  },

  "game020": {
    "name": "Stardew Valley",
    "price": "699000",
    "discount": "25",
    "photo": [
      "./images/Market/Stardew1.jpg",
      "./images/Market/Stardew2.jpg",
      "./images/Market/Stardew3.jpg",
      "./images/Market/Stardew4.jpg",
      "./images/Market/Stardew5.jpg",
    ],
    "logo": "./images/Market/Stardew-logo.jpg",
    "developer": "ConcernedApe",
    "releaseDate": "2016-02-26",
    "platform": ["PC", "PS", "Xbox", "Switch"],
    "genre": ["Xây dựng"],
    "ageRating": "12+",
    "information": "Stardew Valley mang đậm tính thư giãn với việc trồng trọt, chăn nuôi và tương tác cùng dân cư, đồng thời mở rộng bằng các nhiệm vụ khám phá hang động và hẹn hò.",
  },

  "game021": {
    "name": "Terraria",
    "price": "150000",
    "discount": "30",
    "photo": [
      "./images/Market/Terraria1.jpg",
      "./images/Market/Terraria2.jpg",
      "./images/Market/Terraria3.jpg",
      "./images/Market/Terraria4.jpg",
      "./images/Market/Terraria5.jpg",
    ],
    "logo": "./images/Market/Terraria-logo.jpg",
    "developer": "Re-Logic",
    "releaseDate": "2011-05-16",
    "platform": ["PC", "PS", "Xbox", "Switch", "Mobile"],
    "genre": ["Xây dựng", "Khám phá"],
    "ageRating": "12+",
    "information": "Terraria là một thế giới 2D sandbox rộng lớn, nơi người chơi có thể xây dựng, chiến đấu với quái vật và khám phá hàng trăm loại vật phẩm và sinh vật khác nhau.",
  }
};
